#!/usr/bin/env python3
"""The accuracy of a reconstruction at surveyed points it was not fitted to.

A checkpoint is a surveyed point, marked in the photos like a ground control
point, that the adjustment never saw. Here each one is located from its marks
with the reconstruction's own cameras (the rays through the marked pixels are
intersected) and compared with its surveyed position. The differences are the
checkpoint errors: what a surveyor reports as the accuracy of the job.

    checkpoint-report.py --opensfm <project>/opensfm --gcp gcp_list.txt --out <folder>
                         [--title "..."] [--lang en|es|both]

The file is in OpenDroneMap's ground-control format:

    EPSG:32719                      (or a proj string, or "WGS84 UTM 19S")
    x y z pixel_x pixel_y image.jpg name

With `--gcp`, the one file a client uploads, a point whose name starts with CHK
or CHECK is a checkpoint and the rest are control (the engine leaves the
checkpoints out of the adjustment by the same rule: add-checkpoints.py);
`--all-check` treats every point as a checkpoint, for a run that did not use
the file to fit. The two can also be given apart: `--checkpoints file
[--control file]`. Control points are reported beside the checkpoints, for
comparison.

Writes checkpoints.json and checkpoints.pdf in --out (`--lang both`: English as
checkpoints.pdf, Spanish as checkpoints.es.pdf). Exit 0 when a report was
written or the file holds no checkpoint, 2 when no checkpoint is marked in two
photos of the reconstruction, 1 on bad input.

    checkpoint-report.py --self-test
"""
import argparse
import json
import math
import os
import sys

import numpy as np

MIN_VIEWS = 2


def is_checkpoint(name):
    """The rule shared with the engine (add-checkpoints.py): the point's name says so."""
    return name.upper().startswith(("CHK", "CHECK"))

TEXT = {
    "en": {
        "title": "Checkpoint accuracy report",
        "what": "Surveyed points the adjustment did not use, located from their marks in the photos with the reconstruction's own cameras and compared with their surveyed positions.",
        "summary": "Summary",
        "checkpoints": "Checkpoints",
        "control": "Control points (used in the adjustment)",
        "points": "points", "photos": "photos", "views": "Views",
        "h_rmse": "Horizontal RMSE", "v_rmse": "Vertical RMSE", "thousands": ",",
        "median_box": "Median error, horizontal / vertical",
        "rmse": "RMSE", "mean": "Mean", "median": "Median", "max": "Largest", "p68": "68% within",
        "east": "East", "north": "North", "height": "Height", "horizontal": "Horizontal", "vertical": "Vertical", "d3": "3D",
        "name": "Point", "plan": "Plan of the checkpoints, with the horizontal error of each drawn %d times its size",
        "scale": "errors drawn x%d",
        "method": "Method",
        "method_text": "Each point is intersected from the rays through its marks; a point needs marks in at least two photos of the reconstruction. Errors are reconstruction minus survey, in metres, in local east / north / height. RMSE is the root of the mean of the squared errors. The figures describe the camera network at these points; products made from it (orthophoto, surface models) add their own resolution.",
        "few": "Fewer than five checkpoints: the figures describe these points, not the whole survey.",
        "edge": "Points seen in fewer than %d photos (usually at the edge of the flight) are less reliable: %s.",
        "skipped": "Not reported (fewer than two marked photos in the reconstruction): %s.",
        "ctrl_note": "Control points fit by construction; their errors say how well the adjustment honoured them, not how accurate the survey is.",
        "units": "m",
        "generated": "Generated by CloudODM",
    },
    "es": {
        "title": "Informe de exactitud en puntos de chequeo",
        "what": "Puntos medidos en terreno que el ajuste no usó, ubicados desde sus marcas en las fotos con las cámaras de la propia reconstrucción y comparados con sus posiciones medidas.",
        "summary": "Resumen",
        "checkpoints": "Puntos de chequeo",
        "control": "Puntos de apoyo (usados en el ajuste)",
        "points": "puntos", "photos": "fotos", "views": "Vistas",
        "h_rmse": "RMSE horizontal", "v_rmse": "RMSE vertical", "thousands": ".",
        "median_box": "Error mediano, horizontal / vertical",
        "rmse": "RMSE", "mean": "Media", "median": "Mediana", "max": "Mayor", "p68": "68% dentro de",
        "east": "Este", "north": "Norte", "height": "Altura", "horizontal": "Horizontal", "vertical": "Vertical", "d3": "3D",
        "name": "Punto", "plan": "Planta de los puntos de chequeo, con el error horizontal de cada uno dibujado %d veces su tamaño",
        "scale": "errores dibujados x%d",
        "method": "Método",
        "method_text": "Cada punto se interseca desde los rayos de sus marcas; un punto necesita marcas en al menos dos fotos de la reconstrucción. Los errores son reconstrucción menos medición, en metros, en este / norte / altura locales. El RMSE es la raíz de la media de los errores al cuadrado. Las cifras describen la red de cámaras en estos puntos; los productos derivados (ortofoto, modelos de superficie) agregan su propia resolución.",
        "few": "Menos de cinco puntos de chequeo: las cifras describen estos puntos, no todo el levantamiento.",
        "edge": "Los puntos vistos en menos de %d fotos (normalmente al borde del vuelo) son menos confiables: %s.",
        "skipped": "No informados (menos de dos fotos marcadas en la reconstrucción): %s.",
        "ctrl_note": "Los puntos de apoyo calzan por construcción; sus errores dicen qué tan bien los respetó el ajuste, no qué tan exacto es el levantamiento.",
        "units": "m",
        "generated": "Generado por CloudODM",
    },
}
WEAK_VIEWS = 10


# ── geometry ────────────────────────────────────────────────────────────────

def rodrigues(r):
    r = np.asarray(r, float)
    t = np.linalg.norm(r)
    if t < 1e-12:
        return np.eye(3)
    k = r / t
    K = np.array([[0, -k[2], k[1]], [k[2], 0, -k[0]], [-k[1], k[0], 0]])
    return np.eye(3) + math.sin(t) * K + (1 - math.cos(t)) * K @ K


def distort(cam, x, y):
    k1, k2, k3 = cam.get("k1", 0.0), cam.get("k2", 0.0), cam.get("k3", 0.0)
    p1, p2 = cam.get("p1", 0.0), cam.get("p2", 0.0)
    r2 = x * x + y * y
    rad = 1 + k1 * r2 + k2 * r2 * r2 + k3 * r2 ** 3
    return x * rad + 2 * p1 * x * y + p2 * (r2 + 2 * x * x), y * rad + p1 * (r2 + 2 * y * y) + 2 * p2 * x * y


SUPPORTED = ("perspective", "brown", "simple_radial", "radial")


def ray(shot, cam, px, py):
    """The ray through a pixel (ODM's convention: the centre of the top-left
    pixel is 0,0), as origin and unit direction in the reconstruction's frame."""
    R = rodrigues(shot["rotation"])
    w, h = cam["width"], cam["height"]
    s = max(w, h)
    fx = cam.get("focal_x", cam.get("focal"))
    fy = cam.get("focal_y", fx)
    xd = ((px + 0.5 - w / 2) / s - cam.get("c_x", 0.0)) / fx
    yd = ((py + 0.5 - h / 2) / s - cam.get("c_y", 0.0)) / fy
    x, y = xd, yd
    for _ in range(30):  # undo the lens distortion by fixed-point iteration
        dx, dy = distort(cam, x, y)
        x, y = x + (xd - dx), y + (yd - dy)
    d = R.T @ np.array([x, y, 1.0])
    return -R.T @ np.asarray(shot["translation"], float), d / np.linalg.norm(d)


def intersect(rays):
    """The point nearest to all the rays, and how far the worst ray passes from it."""
    A = np.zeros((3, 3))
    b = np.zeros(3)
    for o, d in rays:
        M = np.eye(3) - np.outer(d, d)
        A += M
        b += M @ o
    X = np.linalg.solve(A, b)
    return X, max(float(np.linalg.norm((np.eye(3) - np.outer(d, d)) @ (X - o))) for o, d in rays)


class Topocentric:
    """Geodetic to the reconstruction's local east/north/up, about its reference."""

    def __init__(self, ref):
        from pyproj import CRS, Transformer
        self._ecef = Transformer.from_crs(CRS.from_epsg(4979), CRS.from_epsg(4978), always_xy=True)
        lat0, lon0 = math.radians(ref["latitude"]), math.radians(ref["longitude"])
        self._x0 = np.array(self._ecef.transform(ref["longitude"], ref["latitude"], ref.get("altitude", 0.0)))
        self._r = np.array([[-math.sin(lon0), math.cos(lon0), 0],
                            [-math.sin(lat0) * math.cos(lon0), -math.sin(lat0) * math.sin(lon0), math.cos(lat0)],
                            [math.cos(lat0) * math.cos(lon0), math.cos(lat0) * math.sin(lon0), math.sin(lat0)]])

    def __call__(self, lon, lat, h):
        return self._r @ (np.array(self._ecef.transform(lon, lat, h)) - self._x0)


# ── input ───────────────────────────────────────────────────────────────────

def parse_crs(header):
    """OpenDroneMap's first line: EPSG:n, a proj string, or 'WGS84 UTM 19S'."""
    from pyproj import CRS
    h = header.strip()
    parts = h.upper().split()
    if len(parts) == 3 and parts[0] == "WGS84" and parts[1] == "UTM":
        zone, south = parts[2][:-1], parts[2][-1] == "S"
        return CRS.from_epsg((32700 if south else 32600) + int(zone))
    if h.upper() == "WGS84":
        return CRS.from_epsg(4326)
    return CRS.from_user_input(h)


def read_points(path, keep=None):
    """{name: {"lonlat_h": (lon, lat, h), "xyz": (x, y, z), "marks": [(image, px, py)]}} from a ground-control file.
    `keep`: "check" for the points named as checkpoints only, "control" for the others, None for all."""
    from pyproj import CRS, Transformer
    with open(path, encoding="utf-8-sig") as f:
        lines = [ln.strip() for ln in f if ln.strip() and not ln.lstrip().startswith("#")]
    if not lines:
        raise ValueError(f"{os.path.basename(path)} is empty")
    crs = parse_crs(lines[0])
    to_wgs = Transformer.from_crs(crs, CRS.from_epsg(4326), always_xy=True)
    points = {}
    for n, ln in enumerate(lines[1:], start=2):
        p = ln.split()
        if len(p) < 6:
            raise ValueError(f"{os.path.basename(path)} line {n}: expected x y z pixel_x pixel_y image [name]")
        x, y, z, px, py = (float(v) for v in p[:5])
        image = p[5]
        # Unnamed points are told apart by their coordinates, as written.
        name = p[6] if len(p) > 6 else f"{p[0]}, {p[1]}"
        if keep is not None and (keep == "check") != (len(p) > 6 and is_checkpoint(p[6])):
            continue
        if name not in points:
            lon, lat = to_wgs.transform(x, y)
            points[name] = {"lonlat_h": (lon, lat, z), "xyz": (x, y, z), "marks": []}
        points[name]["marks"].append((image, px, py))
    return points, crs.to_string()


def load_reconstruction(folder):
    for name in ("reconstruction.topocentric.json", "reconstruction.json"):
        path = os.path.join(folder, name)
        if os.path.exists(path):
            with open(path) as f:
                recs = json.load(f)
            if recs:
                # The largest piece: a split model's smaller parts are not the survey.
                return max(recs, key=lambda r: len(r.get("shots", {}))), name
    raise ValueError("no reconstruction in " + folder)


# ── the measurement ─────────────────────────────────────────────────────────

def measure(points, rec, topo):
    shots, cams = rec["shots"], rec["cameras"]
    by_basename = {os.path.basename(k): k for k in shots}
    rows, skipped = [], []
    for name in sorted(points):
        p = points[name]
        rays = []
        for image, px, py in p["marks"]:
            key = image if image in shots else by_basename.get(os.path.basename(image))
            if key is None:
                continue
            cam = cams[shots[key]["camera"]]
            if cam.get("projection_type", "perspective") not in SUPPORTED:
                raise ValueError(f"camera model {cam.get('projection_type')} is not supported by the checkpoint report")
            rays.append(ray(shots[key], cam, px, py))
        if len(rays) < MIN_VIEWS:
            skipped.append(name)
            continue
        X, miss = intersect(rays)
        e = X - topo(*p["lonlat_h"])
        rows.append({"name": name, "views": len(rays), "dE": float(e[0]), "dN": float(e[1]), "dH": float(e[2]),
                     "horizontal": float(math.hypot(e[0], e[1])), "raysMiss": miss,
                     "x": p["xyz"][0], "y": p["xyz"][1], "z": p["xyz"][2],
                     "east": float(topo(*p["lonlat_h"])[0]), "north": float(topo(*p["lonlat_h"])[1])})
    return rows, skipped


def summarise(rows):
    if not rows:
        return None
    E = np.array([[r["dE"], r["dN"], r["dH"]] for r in rows])
    hz = np.hypot(E[:, 0], E[:, 1])
    vt = np.abs(E[:, 2])
    rmse = np.sqrt((E ** 2).mean(0))
    return {
        "count": len(rows),
        "mean": {"east": float(E[:, 0].mean()), "north": float(E[:, 1].mean()), "height": float(E[:, 2].mean())},
        "rmse": {"east": float(rmse[0]), "north": float(rmse[1]), "height": float(rmse[2]),
                 "horizontal": float(math.hypot(rmse[0], rmse[1])), "d3": float(np.linalg.norm(rmse))},
        "median": {"horizontal": float(np.median(hz)), "vertical": float(np.median(vt))},
        "p68": {"horizontal": float(np.percentile(hz, 68)), "vertical": float(np.percentile(vt, 68))},
        "max": {"horizontal": float(hz.max()), "vertical": float(vt.max())},
    }


def build_report(opensfm, checkpoints, control=None, gcp=None, all_check=False):
    """`gcp`: one file holding both, told apart by name (or all of it checkpoints). Otherwise two files."""
    if gcp:
        pts, crs = read_points(gcp, None if all_check else "check")
        if not pts:
            return None
    else:
        pts, crs = read_points(checkpoints)
    rec, rec_name = load_reconstruction(opensfm)
    with open(os.path.join(opensfm, "reference_lla.json")) as f:
        topo = Topocentric(json.load(f))
    rows, skipped = measure(pts, rec, topo)
    report = {
        "version": 1,
        "reconstruction": {"file": rec_name, "photos": len(rec["shots"])},
        "crs": crs,
        "checkpoints": {"summary": summarise(rows), "points": rows, "skipped": skipped},
        "weakViews": WEAK_VIEWS,
    }
    if (gcp and not all_check) or (control and os.path.exists(control)):
        cpts, _ = read_points(gcp, "control") if gcp else read_points(control)
        crows, cskipped = measure(cpts, rec, topo)
        report["control"] = {"summary": summarise(crows), "points": crows, "skipped": cskipped}
    return report


# ── the document ────────────────────────────────────────────────────────────

def signed(v):
    """+0.012 / -0.012, and plain 0.000 for what rounds to nothing."""
    text = f"{v:+.3f}"
    return "0.000" if text in ("+0.000", "-0.000") else text


def tidy_factor(raw):
    """1, 2, 5, 10, 20, 50, ... not above `raw`."""
    if raw < 1:
        return 1
    m = 10 ** math.floor(math.log10(raw))
    lead = raw / m
    return int(m * (5 if lead >= 5 else 2 if lead >= 2 else 1))


def cm(v):
    text = f"{v * 100:.1f} cm" if abs(v) < 1 else f"{v:.2f} m"
    return text[1:] if text.startswith("-0.0 ") else text  # no "minus zero"


def write_pdf(report, path, title, lang):
    import warnings
    # Written for the PDF library's older calls, which every version still
    # accepts; the newer ones only add a notice per cell to the run's log.
    warnings.filterwarnings("ignore", category=DeprecationWarning)
    from fpdf import FPDF
    t = TEXT[lang]
    S = report["checkpoints"]["summary"]
    rows = report["checkpoints"]["points"]

    def latin(s):  # the built-in fonts are Latin-1
        return s.encode("latin-1", "replace").decode("latin-1")

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(True, 16)
    pdf.add_page()
    W = 210 - 2 * 16
    pdf.set_margins(16, 16, 16)
    pdf.set_xy(16, 16)

    # Every block starts at the left margin: where a cell leaves the cursor
    # differs between versions of the PDF library.
    def para(text, size=9.5, style="", color=(60, 60, 60), h=4.6):
        pdf.set_font("Helvetica", style, size)
        pdf.set_text_color(*color)
        pdf.set_x(16)
        pdf.multi_cell(W, h, latin(text))
        pdf.set_x(16)

    para(t["title"], 17, "B", (20, 20, 20), 8)
    if title:
        para(title, 11, "", (20, 20, 20), 6)
    pdf.ln(1)
    para(t["what"])
    pdf.ln(3)

    # The headline: three figures a surveyor looks for first.
    y0 = pdf.get_y()
    boxes = [(t["h_rmse"], cm(S["rmse"]["horizontal"])),
             (t["v_rmse"], cm(S["rmse"]["height"])),
             (t["median_box"], cm(S["median"]["horizontal"]).replace(" cm", "") + " / " + cm(S["median"]["vertical"])
              if S["median"]["horizontal"] < 1 and S["median"]["vertical"] < 1 else cm(S["median"]["horizontal"]) + " / " + cm(S["median"]["vertical"]))]
    bw = (W - 8) / 3
    for i, (label, value) in enumerate(boxes):
        x = 16 + i * (bw + 4)
        pdf.set_fill_color(240, 244, 238)
        pdf.rect(x, y0, bw, 20, "F")
        pdf.set_xy(x + 3, y0 + 3)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(80, 90, 80)
        pdf.cell(bw - 6, 4, latin(label))
        pdf.set_xy(x + 3, y0 + 8.5)
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(20, 40, 20)
        pdf.cell(bw - 6, 8, latin(value))
    pdf.set_xy(16, y0 + 25)

    def table(header, body, widths, bold_first=False):
        def head():
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_text_color(40, 40, 40)
            pdf.set_fill_color(228, 232, 226)
            x, y = 16, pdf.get_y()
            for i, (hcell, w) in enumerate(zip(header, widths)):
                pdf.set_xy(x, y)
                pdf.cell(w, 6, latin(hcell), 0, 0, "L" if i == 0 else "R", True)
                x += w
            pdf.set_xy(16, y + 6)

        head()
        for n, row in enumerate(body):
            if pdf.get_y() > 272:
                pdf.add_page()
                head()
            pdf.set_fill_color(247, 248, 246)
            pdf.set_text_color(40, 40, 40)
            x, y = 16, pdf.get_y()
            for i, (c, w) in enumerate(zip(row, widths)):
                pdf.set_font("Helvetica", "B" if (bold_first and i == 0) else "", 8.5)
                pdf.set_xy(x, y)
                pdf.cell(w, 5.2, latin(c), 0, 0, "L" if i == 0 else "R", n % 2 == 1)
                x += w
            pdf.set_xy(16, y + 5.2)

    def summary_table(label, s):
        para(label, 11, "B", (20, 20, 20), 6)
        # Median, 68% and largest are sizes of error (no sign): horizontal, and height.
        table(["", t["east"], t["north"], t["height"], t["horizontal"], t["d3"]],
              [[t["rmse"], cm(s["rmse"]["east"]), cm(s["rmse"]["north"]), cm(s["rmse"]["height"]), cm(s["rmse"]["horizontal"]), cm(s["rmse"]["d3"])],
               [t["mean"], cm(s["mean"]["east"]), cm(s["mean"]["north"]), cm(s["mean"]["height"]), "", ""],
               [t["median"], "", "", cm(s["median"]["vertical"]), cm(s["median"]["horizontal"]), ""],
               [t["p68"], "", "", cm(s["p68"]["vertical"]), cm(s["p68"]["horizontal"]), ""],
               [t["max"], "", "", cm(s["max"]["vertical"]), cm(s["max"]["horizontal"]), ""]],
              [38, 28, 28, 28, 28, 28], bold_first=True)
        pdf.ln(3)

    summary_table(f"{t['checkpoints']}: {S['count']} {t['points']}, {format(report['reconstruction']['photos'], ',').replace(',', t['thousands'])} {t['photos']}", S)
    notes = []
    if S["count"] < 5:
        notes.append(t["few"])
    weak = [r["name"] for r in rows if r["views"] < WEAK_VIEWS]
    if weak and len(weak) < len(rows):
        notes.append(t["edge"] % (WEAK_VIEWS, ", ".join(weak)))
    if report["checkpoints"]["skipped"]:
        notes.append(t["skipped"] % ", ".join(report["checkpoints"]["skipped"]))
    for nline in notes:
        para(nline, 8.5, "I")
    if notes:
        pdf.ln(2)

    # Plan: where the points are and which way each one is off.
    if len(rows) >= 3:
        xs = np.array([r["east"] for r in rows])
        ys = np.array([r["north"] for r in rows])
        span = max(xs.max() - xs.min(), ys.max() - ys.min(), 1.0)
        box = 84.0
        if pdf.get_y() + box + 14 > 280:
            pdf.add_page()
        gy = pdf.get_y() + 1
        gx = 16 + (W - box) / 2
        pdf.set_draw_color(200, 205, 198)
        pdf.rect(gx, gy, box, box)
        worst = max(r["horizontal"] for r in rows) or 1e-6
        pad = 12.0  # room for the error lines of points at the edge
        k = (box - 2 * pad) / span
        factor = tidy_factor((pad / k) / worst)  # the worst error stays inside the frame

        def to_page(e, n):
            return (gx + pad + (e - xs.min()) * k + ((span - (xs.max() - xs.min())) * k) / 2,
                    gy + box - pad - (n - ys.min()) * k - ((span - (ys.max() - ys.min())) * k) / 2)

        for r in rows:
            px, py = to_page(r["east"], r["north"])
            qx, qy = px + r["dE"] * factor * k, py - r["dN"] * factor * k
            pdf.set_draw_color(196, 72, 48)
            pdf.set_line_width(0.35)
            pdf.line(px, py, qx, qy)
            pdf.set_fill_color(40, 70, 40)
            pdf.ellipse(px - 0.7, py - 0.7, 1.4, 1.4, "F")
        pdf.set_line_width(0.2)
        pdf.set_xy(16, gy + box + 1.5)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(90, 90, 90)
        pdf.cell(W, 4, latin(t["plan"] % factor), 0, 0, "C")
        pdf.set_xy(16, gy + box + 5.5)
        pdf.ln(3)

    para(t["checkpoints"], 11, "B", (20, 20, 20), 6)
    table([t["name"], t["views"], "dE", "dN", "dH", t["horizontal"]],
          [[r["name"], str(r["views"]), signed(r["dE"]), signed(r["dN"]), signed(r["dH"]), f"{r['horizontal']:.3f}"] for r in rows],
          [50, 20, 27, 27, 27, 27])
    pdf.ln(3)

    C = report.get("control")
    if C and C["summary"]:
        summary_table(f"{t['control']}: {C['summary']['count']} {t['points']}", C["summary"])
        para(t["ctrl_note"], 8.5, "I")
        pdf.ln(2)

    para(t["method"], 11, "B", (20, 20, 20), 6)
    para(t["method_text"], 8.8)
    pdf.ln(2)
    para(f"{t['generated']} - {report['crs']} - {t['units']}", 7.5, "", (130, 130, 130), 4)
    pdf.output(path)


# ── self-test ───────────────────────────────────────────────────────────────

def self_test():
    """A point of known position, seen by cameras with a distorting lens: marks
    made by projecting it must intersect back onto it."""
    rng = np.random.default_rng(7)
    cam = {"width": 8000, "height": 6000, "focal": 0.9, "k1": -0.05, "k2": 0.02, "p1": 0.001, "p2": -0.0005, "c_x": 0.003, "c_y": -0.002,
           "projection_type": "brown", "focal_x": 0.9, "focal_y": 0.9, "k3": 0.0}
    X = np.array([12.0, -7.0, 3.0])
    shots, marks = {}, []
    for i in range(6):
        c = np.array([rng.uniform(-40, 40), rng.uniform(-40, 40), 60.0 + rng.uniform(-3, 3)])
        # Looking down (half a turn about a horizontal axis), turned about the
        # vertical and tilted a little.
        a = rng.uniform(0, math.pi)
        axis = np.array([math.cos(a), math.sin(a), rng.uniform(-0.05, 0.05)])
        rvec = axis / np.linalg.norm(axis) * (math.pi + rng.uniform(-0.1, 0.1))
        R = rodrigues(rvec)  # world to camera
        name = f"p{i}.jpg"
        shots[name] = {"rotation": list(rvec), "translation": list(-R @ c), "camera": "c"}
        pc = R @ (X - c)
        assert pc[2] > 0, "the point is in front of the camera"
        x, y = pc[0] / pc[2], pc[1] / pc[2]
        xd, yd = distort(cam, x, y)
        s = max(cam["width"], cam["height"])
        px = (xd * cam["focal_x"] + cam["c_x"]) * s + cam["width"] / 2 - 0.5
        py = (yd * cam["focal_y"] + cam["c_y"]) * s + cam["height"] / 2 - 0.5
        marks.append((name, px, py))
        o, d = ray(shots[name], cam, px, py)
        assert np.linalg.norm(o - c) < 1e-9, "camera centre"
    got, miss = intersect([ray(shots[n], cam, px, py) for n, px, py in marks])
    assert np.linalg.norm(got - X) < 1e-6 and miss < 1e-6, (got, miss)
    # A mark that is 10 px off moves the point by about 10 px on the ground, not more.
    bad = [(marks[0][0], marks[0][1] + 10, marks[0][2])] + marks[1:]
    off, _ = intersect([ray(shots[n], cam, px, py) for n, px, py in bad])
    gsd = 60.0 / (cam["focal"] * 8000)
    assert 0 < np.linalg.norm(off - X) < 10 * gsd, np.linalg.norm(off - X)
    s = summarise([{"dE": 0.03, "dN": 0.04, "dH": -0.12}, {"dE": -0.03, "dN": -0.04, "dH": 0.12}])
    assert abs(s["rmse"]["horizontal"] - 0.05) < 1e-12 and abs(s["rmse"]["height"] - 0.12) < 1e-12 and abs(s["mean"]["east"]) < 1e-12
    assert [tidy_factor(v) for v in (0.3, 1, 3.9, 7, 49, 500)] == [1, 1, 2, 5, 20, 500]
    assert signed(-0.0002) == "0.000" and signed(0.0126) == "+0.013" and signed(-0.5) == "-0.500"
    assert cm(-0.0001) == "0.0 cm" and cm(0.125) == "12.5 cm" and cm(-0.03) == "-3.0 cm" and cm(1.5) == "1.50 m"
    assert is_checkpoint("chk-3") and is_checkpoint("Check_A1") and not is_checkpoint("GCP3") and not is_checkpoint("A-CHK")
    assert parse_crs("WGS84 UTM 19S").to_epsg() == 32719 and parse_crs("EPSG:4326").to_epsg() == 4326
    print("self-test ok")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--opensfm")
    ap.add_argument("--gcp")
    ap.add_argument("--all-check", action="store_true")
    ap.add_argument("--checkpoints")
    ap.add_argument("--control")
    ap.add_argument("--out")
    ap.add_argument("--title", default="")
    ap.add_argument("--lang", default="en", choices=sorted(TEXT) + ["both"])
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    if not (a.opensfm and a.out and (a.gcp or a.checkpoints)):
        ap.error("--opensfm, --out and one of --gcp / --checkpoints are required")
    try:
        report = build_report(a.opensfm, a.checkpoints, a.control, a.gcp, a.all_check)
    except (ValueError, OSError, KeyError) as ex:
        print(f"checkpoint report: {ex}", file=sys.stderr)
        sys.exit(1)
    if report is None:
        print("checkpoint report: the ground-control file names no checkpoint (CHK...)")
        return
    os.makedirs(a.out, exist_ok=True)
    with open(os.path.join(a.out, "checkpoints.json"), "w") as f:
        json.dump(report, f, indent=1)
    S = report["checkpoints"]["summary"]
    if S is None:
        print("checkpoint report: no checkpoint is marked in two photos of the reconstruction", file=sys.stderr)
        sys.exit(2)
    if a.lang == "both":
        write_pdf(report, os.path.join(a.out, "checkpoints.pdf"), a.title, "en")
        write_pdf(report, os.path.join(a.out, "checkpoints.es.pdf"), a.title, "es")
    else:
        write_pdf(report, os.path.join(a.out, "checkpoints.pdf"), a.title, a.lang)
    print(f"checkpoints: {S['count']} points, RMSE horizontal {S['rmse']['horizontal']:.3f} m, vertical {S['rmse']['height']:.3f} m, "
          f"median {S['median']['horizontal']:.3f} / {S['median']['vertical']:.3f} m")


if __name__ == "__main__":
    main()
